apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    app: elasticsearch
  namespace: es
spec:
  ports:
  - port: 9200
    name: search
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  labels:
    app: elasticsearch
  namespace: es
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "elasticsearch"
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      terminationGracePeriodSeconds: 20
      initContainers:
      - name: setperms
        image: busybox
        command:
         - sh
         - "-c"
         - "chmod -R g+rwx /data; chgrp -R 1000 /data"
        volumeMounts:
        - name: es-data
          mountPath: /data
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.name
            value: k8s-tf-cluster
          - name: discovery.seed_hosts
            value: es.es.svc
          - name: cluster.initial_master_nodes
            value: es-0,es-1,es-2
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: search
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs"
      resources:
        requests:
          storage: 20Gi