apiVersion: v1
kind: Pod
metadata:
  labels:
    app: es-single
  name: es-single
spec:
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    name: elasticearch
    env:
      - name: discovery.type
        value: single-node
      - name: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
    ports:
      - name: search
        containerPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-single
  name: es-single
spec:
  ports:
  - name: search
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-single
  type: ClusterIP
