apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-vol-a
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      az: eu-central-1a

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-vol-b
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      az: eu-central-1b