apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-controller
  serviceName: snapshot-controller
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      containers:
      - args:
        - --v=5
        - --leader-election=false
        image: quay.io/k8scsi/snapshot-controller:v2.0.1
        name: snapshot-controller
      serviceAccount: snapshot-controller
