apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-csi
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-csi-immediate
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
volumeBindingMode: Immediate

---

apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: ebs-csi
driver: ebs.csi.aws.com
deletionPolicy: Delete
